# -*- coding: utf-8 -*-
"""Pregunta 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13SLJvIw4SFO6VYIBANpmIUM4AYo-j4JS
"""

# Importamos librerias 
import pandas as pd
import matplotlib.pyplot as plt

# Cargo archivos
uploaded = files.upload()

## Creamos un dataframe a partir del fichero csv
df = pd.read_csv("titanic.csv",sep = ",")

"""1. Diagrama de sectores con los fallecidos y supervivientes"""

# Creamos la figura y los ejes
fig, ax = plt.subplots()
# Diagrama de sectores de fallecidos y supervivientes
df.Survived.value_counts().plot(kind = "pie", labels = ["Muertos", "Supervivientes"], title = "Distribución de supervivientes")
plt.show()



"""2. Histograma con las edades"""

df.Age.plot(kind = "hist", title = "Histograma de edades")

plt.show()

"""3. Diagrama de barras con el número de personas en cada clase."""

df.Pclass.value_counts().plot(kind = "bar", title = "Número de personas por clase")

plt.show()

"""4. Diagrama de barras con el número de personas fallecidas y supervivientes en cada clase"""

df.groupby(["Pclass", "Survived"]).size().unstack().plot(kind = "bar", title = "Número de personas fallecidas y supervivientes por clase")

plt.show()

"""5. Diagrama de barras con el número de personas fallecidas y supervivientes acumuladas en cada clase"""

df.groupby(["Pclass", "Survived"]).size().unstack().plot(kind = "bar", stacked = True, title = "Número de personas fallecidas y supervivientes por clase")

plt.show()

